name: Python package

on: 
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    env:
      OPENTRANSPORT_CREDENTIAL: ${{secrets.OPENTRANSPORT_CREDENTIAL}}

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up gcloud Cloud SDK environment
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS}}'
          
      - name: Test with pytest
        run: |
          pytest tests.py
          
      - name: Deploy the function
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'predict'
          runtime: 'python311'
          memory_mb: '8192'
          region: "us-east1"
